<?php

declare(strict_types=1);

return [
    'ar-XA' => 'Arabic',
    'bg' => 'Bulgarian',
    'hr' => 'Croatian',
    'cs' => 'Czech',
    'da' => 'Danish',
    'de' => 'German',
    'el' => 'Greek',
    'en' => 'English',
    'et' => 'Estonian',
    'es' => 'Spanish',
    'fi' => 'Finnish',
    'fr' => 'French',
    'ga' => 'Irish',
    'hi' => 'Hindi',
    'hu' => 'Hungarian',
    'he' => 'Hebrew',
    'it' => 'Italian',
    'ja' => 'Japanese',
    'ko' => 'Korean',
    'lv' => 'Latvian',
    'lt' => 'Lithuanian',
    'nl' => 'Dutch',
    'no' => 'Norwegian',
    'pl' => 'Polish',
    'pt' => 'Portuguese',
    'sv' => 'Swedish',
    'ro' => 'Romanian',
    'ru' => 'Russian',
    'sr-CS' => 'Serbian',
    'sk' => 'Slovak',
    'sl' => 'Slovenian',
    'th' => 'Thai',
    'tr' => 'Turkish',
    'uk-UA' => 'Ukrainian',
    'zh-chs' => 'Chinese (Simplified)',
    'zh-cht' => 'Chinese (Traditional)',
];
